# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa05d76ca0448016e505ed0685c2e6ee853946cd8a12a697e010a457c86febc739ffc0fd6e4e99d7cd8c5de73ff8727376739f1bb036329092952c922d13d68

test:
  secret_key_base: a2e0e918b70d787611d2fa5a55bb692760ce810ddcfd624fc4d32ef1b3adb4c900f96ae6dd80eb7c0948baac47edfa0c178188c43f3246b2790163cbbd350777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
